name: app_flutter
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  http: ^1.2.2
  shared_preferences: ^2.0.13
  go_router: ^14.3.0
  flutter_secure_storage: ^9.2.2
  connectivity_plus: ^6.1.0
  dart_jsonwebtoken: ^2.14.1
  jwt_decode: ^0.3.1
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  url_launcher: ^6.3.1
  image_picker: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/poster_03.jpg
    - assets/img.png
    - assets/logo.png
    - assets/images/hcm.jpg
    - assets/images/hanoi.jpg
    - assets/images/danang.jpg
    - assets/data/vn_units.json
